################################## Настройки приложения / Application Settings
app:
  port: 43000
  hostname: tlss.lv.local
  # hostname: localhost
  protocol: https # http или https / http or https
  certFile: https/tlss.lv.local.pem
  keyFile: https/tlss.lv.local.key

################################## Настройки логирования / Logging Settings
logging:
  level: info # debug, info, warn, error
  format: text # json, text
  output: stdout # file, stdout, both
  file: logs/tlss.log
  maxSize: 100 # MB
  maxBackups: 3
  maxAge: 28 # days / дней

################################## Настройки авторизации при старте приложения / Authorization Settings for application start
login:
  authConfig: true # true - использовать конфигурацию из config.yaml, false - использовать ручной ввод / true - use config.yaml settings, false - use manual input
  username: admin
  password: 1gd5hfg5jdgsyrtf
  salt: mysecuresalt123

################################## Настройки базы данных / Database Settings
database:
  path: db/database.db

################################## Первичные имена для корневого CA и подчиненного CA / Default names for Root CA and Sub CA
root_ca_tlss:
  commonName: TLSS Root CA

sub_ca_tlss:
  commonName: TLSS Sub CA

################################## Настройки CRL / CRL Settings
CAcrl:
  crlURL: https://tlss.lv.local:43000/api/v1/crl/bundleca/pem # der или pem большинство прокси работают с pem / der or pem (most proxies work with pem)
  unit: hours # minutes, seconds, hours
  updateInterval: 24 # minutes 12 hours / интервал обновления: 12 часов

################################## Настройки CA / CA Settings
CApath:
  db: true # true - сохранять в базе данных / save to database
  server: false # false - сохранять на сервере / save to server

ca_tlss:
  path_cert: ./root_ca_tlss/root_ca_tlss.pem
  path_key: ./root_ca_tlss/root_ca_tlss.key

################################## Настройки SSH при добавлении сервера / SSH Settings for Server Addition
add_server:
  unit: seconds # minutes, seconds, hours
  waitingToConnect: 3 

################################## Настройки чекеров / Checker Settings
# Проверка доступности TCP портов / TCP port availability check
checkServer:
  unit: seconds # minutes, seconds, hours
  checkServerInterval: 10

# Проверка валидности сертификатов / Certificate validity check
certsValidation:
  unit: seconds # minutes, seconds, hours
  certsValidationInterval: 30 

# Пересоздание сертификатов / Certificate recreation
recreateCerts:
  unit: seconds # minutes, seconds, hours
  recreateCertsInterval: 5

################################## Настройки мониторинга работы чекеров / Checker Monitoring Settings
monitor:
  unitTCP: seconds # minutes, seconds, hours
  TCPInterval: 5
  unitRecreateCerts: seconds # minutes, seconds, hours
  RecreateCertsInterval: 3
  unitCheckValidCerts: seconds # minutes, seconds, hours
  CheckValidCertsInterval: 10