app:
  port: 43000
  hostname: tlss.lv.local
  # hostname: localhost
  # useHTTPS: true
  protocol: https
  certFile: ./https/tlss.lv.local.pem
  keyFile: ./https/tlss.lv.local.key

# Временно для отладки
login:
  username: admin
  password: 1gd5hfg5jdgsyrtf

database:
  path: ./db/database.db
checkServer:
  time: 30 # seconds

ca_tlss:
  path_cert: ./root_ca_tlss/root_ca_tlss.pem
  path_key: ./root_ca_tlss/root_ca_tlss.key

root_ca_tlss:
  commonName: TLSS Root CA

sub_ca_tlss:
  commonName: TLSS Sub CA

add_server:
  waitingToConnect: 3 # seconds


CAcrl:
  crlURL: https://tlss.lv.local:43000/api/v1/crl/bundleca/der
  updateInterval: 24 # minutes 12 hours
  version: 2

# выбираем где сохранять корневой сертификат и закрытый ключ
CApath:
  db: true
  server: false

certsValidation:
  time: 30 # minutes

recreateCerts:
  time: 1 # minutes 12 hours
