app:
  port: 43000
  hostname: tlss.lv.local
  # hostname: localhost
  protocol: https
  certFile: ./https/tlss.lv.local.pem
  keyFile: ./https/tlss.lv.local.key

# Временно для отладки
login:
  username: admin
  password: 1gd5hfg5jdgsyrtf
  salt: mysecuresalt123

database:
  path: ./db/database.db
checkServer:
  unit: seconds # minutes, seconds, hours
  checkServerInterval: 10

monitor:
  unitTCP: seconds # minutes, seconds, hours
  TCPInterval: 5
  unitRecreateCerts: seconds # minutes, seconds, hours
  RecreateCertsInterval: 3
  unitCheckValidCerts: seconds # minutes, seconds, hours
  CheckValidCertsInterval: 10

ca_tlss:
  path_cert: ./root_ca_tlss/root_ca_tlss.pem
  path_key: ./root_ca_tlss/root_ca_tlss.key

root_ca_tlss:
  commonName: TLSS Root CA

sub_ca_tlss:
  commonName: TLSS Sub CA

add_server:
  unit: seconds # minutes, seconds, hours
  waitingToConnect: 3 


CAcrl:
  crlURL: https://tlss.lv.local:43000/api/v1/crl/bundleca/der
  unit: hours # minutes, seconds, hours
  updateInterval: 24 # minutes 12 hours
  version: 2

# выбираем где сохранять корневой сертификат и закрытый ключ
CApath:
  db: true
  server: false

certsValidation:
  unit: seconds # minutes, seconds, hours
  certsValidationInterval: 30 

recreateCerts:
  unit: seconds # minutes, seconds, hours
  recreateCertsInterval: 5
